
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/merge::ScanInfo",
  "LCGReflex/std::vector<merge::ScanInfo>",
  "LCGReflex/edm::Wrapper<std::vector<merge::ScanInfo> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

