BINS := lar_update_rel \
	lar_srt_bootstrap \
	addpkg_svn \
	srt_environment_lar \
	lar_update_testrel \
	lar_build \
	build_larsoft.csh \
	make_lar_build_log \
	update_lar_doxygen.csh \
	ack

SCRIPTS := $(BINS)

########################################################################
include SoftRelTools/standard.mk
